language: node_js
node_js:
  - "node"
  - "6"
before_script:
- export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
- ./node_modules/lighthouse/lighthouse-core/scripts/download-chrome.sh
cache:
  directories:
    - node_modules
notifications:
  email: false
