language: node_js
node_js:
  - "node"
  - "6"
dist: trusty
before_script:
- export DISPLAY=:99.0
- export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
- sh -e /etc/init.d/xvfb start
- ./node_modules/lighthouse/lighthouse-core/scripts/download-chrome.sh
cache:
  directories:
    - node_modules
notifications:
  email: false
